= [[Produktregel]] Die Produktregel und die Quotientenregel
:stem: 
:toc: left
:toc-title: Inhaltsverzeichnis
:sectnums:
:icons: font
:keywords: ableitung, produktregel

== Die Produktregel
=== Motivation [[Motivation]]

Die Notwendigkeit der Produktregel ergibt sich aus folgendem Beispiel:

====
*Aufgabe:*

Bilde die Ableitungen von stem:[f(x)=x^2 * x^3] und stem:[g(x)=x^5].

*Lösung:*

Beide Funktionen haben die gleiche Ableitung stem:[f'(x)=g'(x)=5x^4], da stem:[f(x)=x^2*x^3=x^5=g(x)], wodurch auch deren Ableitungen identisch sein müssen.
====

[WARNING]
====
Ein häufiger Fehler ist, dass für stem:[f'(x)=2x * 3x ^2] berechnet wird, da die beiden Faktoren stem:[x^2] und stem:[x^3] einzeln abgeleitet werden und das Produkt aus den Ergebnissen gebildet wird. Diese Vorgehensweise ist offensichtlich falsch.
====

Wir werden in diesem Kapitel eine Regel, die sogenannte *Produktregel* kennenlernen, mit deren Hilfe man die Ableitung von stem:[f(x)=x^2*x^3] direkt berechnen kann.

=== Herleitung

Wir betrachten im folgenden eine Funktion stem:[p(x)=f(x)*g(x)], deren Ableitung stem:[p'(x)] bestimmt werden soll.


[NOTE]
====
Bezogen auf obiges Beispiel wäre stem:[f(x)=x^2] und stem:[g(x)=x^3].
====

Wir leiten die Ableitungsregel für ein solches Produkt zweier Funktionen mit Hilfe des Differenzenquotienten her:

[stem]
++++
{p(x+h)-p(x)}/h={f(x+h)*g(x+h)-f(x)*g(x)}/h
++++

Nun verwendet man einen Trick, indem man eine _geschickte Null_ zum Zähler addiert, nämlich

[stem]
++++
0=-f(x)*g(x+h)+f(x)*g(x+h)
++++

Fügt man diese "Null" in den Zähler ein, so ändert sich dieser vom Wert her nicht. Somit erhält man als Ausdruck:

[stem]
++++
{f(x+h)*g(x+h)-f(x)*g(x+h)+f(x)*g(x+h) -f(x)*g(x)}/h
++++

Den Bruch kann man nun auseinanderziehen zu

[stem]
++++
{f(x+h)*g(x+h)-f(x)*g(x+h)}/h+{f(x)*g(x+h) -f(x)*g(x)}/h
++++

Im vorderen Teil kann man stem:[g(x+h)] ausklammern, im hinteren Teil stem:[f(x)], also:

[stem]
++++
g(x+h)*{f(x+h)-f(x)}/h + f(x) *{g(x+h)-g(x)}/h
++++

Lässt man nun h gegen 0 laufen, so erhält man den _Differentialquotienten_, der der Ableitung von stem:[p(x)] entspricht.

[IMPORTANT]
.Nicht vergessen:
====
stem:[lim_{h->0} {f(x+h)-f(x)}/h =f'(x)] und stem:[lim_{h->0} {g(x+h)-g(x)}/h=g'(x)]
====

Somit erhält man insgesamt die 

====
*Produktregel*:
[stem]
++++
p'(x)=(f(x)*g(x))'=f(x)*g'(x)+f'(x)*g(x)
++++
====

=== Beispiele
[loweralpha]
. Gehen wir zurück zu unserem Anfangsbeispiel: Dort war zunächst die Ableitung von stem:[x^2*x^3] zu berechnen.
+
Zunächst benötigt man stem:[f(x)], stem:[g(x)] und die zugehörigen Ableitungen:
+
|====
|stem:[f(x)]|stem:[x^2]
|stem:[g(x)]|stem:[x^3]
|stem:[f'(x)]|stem:[2x]
|stem:[g'(x)]|stem:[3x^2]
|====
+
Somit ergibt die Produktregel:
+
[stem]
++++
(x^2*x^3)'=x^2*3x^2+2x*x^3=3x^4+2x^4=5x^4
++++
+
Der Vergleich mit <<Motivation,dem Einstiegsbeispiel>> zeigt, dass mit Hilfe der Produktregel nun tatächlich das Gleiche herauskommt, wie beim direkten Ableiten von stem:[x^5].

. Ableitung von stem:[sin(x)*cos(x)]:
+
[stem]
++++
(sin(x)*cos(x))'=
++++
+
[stem]
++++
(sin(x))'*cos(x)+sin(x)*(cos(x))'= 
++++
+
[stem]
++++
cos(x)*cos(x)+sin(x)*(-sin(x))=
++++
+
[stem]
++++
cos^2(x)-sin^2(x)  
++++

== Die Quotientenregel
=== Herleitung

Mit Hilfe der Produktregel lassen sich auch Quotienten zweier Funktionen ableiten, also Funktionen der Form stem:[f(x)={u(x)}/{v(x)}].

Eine einfache Herleitung gelingt mit Hilfe von Produkt- und Kettenregel: Zunächst schreiben wir stem:[f(x)] mit Hilfe der Potenzgesetze um zu stem:[f(x)=u(x) * (v(x))^{-1}].

Wendet man nun die Produktregel in Verbindung mit der Kettenregel an, so erhält man

stem:[f'(x)=u'(x)*(v(x))^{-1}+u(x)*(-1)*(v(x))^{-2}*v'(x)]

Im letzten Teil muss man gemäß der Kettenregel noch mit stem:[v'(x)] *nachdifferenzieren*, da dies der Ableitung der inneren Funktion entspricht.
Wechselt man von der Potenzschreibweise wieder in die normale Bruchschreibweise, so entspricht dies dem Ausdruck

stem:[f'(x)={u'(x)}/{v(x)}-{u(x)*v'(x)}/{(v(x))^2}]

Bringt man den linken Bruch auch auf den Nenner stem:[(v(x))^2] so lässt sich das Ergebnis zusammenfassen zur

====
*Quotientenregel:*

Ist stem:[f(x)={u(x)}/{v(x)}] mit stem:[u] und stem:[v] differenzierbar, so ist die Ableitung

stem:[f'(x)={u'(x)*v(x)-u(x)*v'(x)}/{(v(x))^2}]
====

[NOTE]
====
Als *Merkregel* kann hier auch die Formel dienen:

stem:[{NAZ-ZAN}/{N^2}]

Sie steht für "Nenner [mal] Ableitung Zähler minus Zähler [mal] Ableitung Nenner. Und alles durch den Nenner im Quadrat dividiert. 
====

=== Beispiel

====
*Aufgabe:*

Bilde die Ableitung von stem:[f(x)={sin(x)}/{cos(x)}].
====

*Lösung:*

stem:[u(x)=sin(x)], stem:[u'(x)=cos(x)], stem:[v(x)=cos(x)] und stem:[v'(x)=-sin(x)].

Eingesetzt in die Formel der Quotientenregel erhält man

stem:[f'(x)={cos(x)*cos(x)-sin(x)*(-sin(x))}/{(cos(x))^2}=]

stem:[{(cos(x))^2+(sin(x))^2}/{(cos(x))^2}]

[NOTE]
====
stem:[{sin(x)}/{cos(x)}] ist die Definition des Tangens von x, also stem:[tan(x)={sin(x)}/{cos(x)}].

Außerdem gilt: stem:[(sin(x))^2+(cos(x))^2=1], so dass sich das Ergebnis der Aufgabe vereinfachen lässt zu:

stem:[(tan(x))' = 1/ {(cos(x))^2}]
====


